let fruits = ["Banana", "Apples", "Oranges", "Blueberries"];
let newfruits = myfruits.filter(function(f) { return f !== 'Banana' });
console.log(newfruits);
var s = newfruits.sort(newfruits);
console.log(s);
newfruits.splice(1, 1, kiwi); 
console.log(newfruits) ;
newfruits.pop(Apples) ;
console.log(newfruits) ;
newfruits.sort(();
	console.log(newfruits) ;
