# Generated by Django 4.1.2 on 2022-10-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='liste',
        ),
    ]
